### ISSUE TITLE
Is this still in development?

### ISSUE THREAD

**Issue by jamescallen246** [FGRE/steins-gate-new#2]

**Comment by krofna** [comment]
Yeah. I haven't abandoned this project. I put tons of work into it in 2018 (and was actually trying to finish it once and for all) and i plan to work on it more this summer when I'm done with exams. It kinda sucks that its taking this long to complete especially because now it's actually very, very near being fully functional, but I've simply been involved into too many things to find spare time.

There's actually only _few_ things that need to be done:
- Writing tests for every function and documenting them (and the whole engine) precisely. This is easy but time consuming. It took up most of the time I put into this project in 2018. It's a nice place to start if you're willing to contribute :) I'd be happy to introduce the workflow to anyone willing to put their time into it :)
- Running through the game and just making sure that it can be completed, mostly fixing the phone code. A bit more difficult, also time consuming.
- Save/Load. This is difficult reverse engineering work. It will be the biggest hurdle.

**Comment by jamescallen246** [comment]
Thank you for this reply! I really appreciate it! I'm glad that this project is still in development since this is a really cool project. Also getting this to work on Linux and Darwin would be fantastic! :)
